### ISSUE TITLE
explain in docs how to run tests

### ISSUE THREAD

**Issue by dimpase** [kimwalisch/primecount#12]
Apparently there is a testsuite in `test/`, but no info on how to actually use it is provided.

**Comment by kimwalisch** [comment]
> Apparently there is a testsuite in test/, but no info on how to actually use it is provided.

I have now added a ```README.md``` to the test directory.

You can run the test suite by executing the following commands from the root primecount directory:

```
cmake -DBUILD_TESTS=ON .
make -j
make test
```

**Comment by dimpase** [comment]
On 15 Mar 2018 07:52, "Kim Walisch" <notifications@github.com> wrote:

Apparently there is a testsuite in test/, but no info on how to actually
use it is provided.

I have now added a README.md to the test directory.

You can run the test suite by executing the following commands from the
root primecount directory:

cmake -DBUILD_TESTS=ON .
make -j
make test


This is a very non-standard design. Normally you would create all the
Makefiles, and afterwards make the targets you need.
This is why I was totally at loss what to do in order to run tests, as
there was no Makefile at that directory.

As well, the main README ought to mention tests, as the presense of the
testsuite could be overlooked otherwise.

 —
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kimwalisch/primecount/issues/12#issuecomment-373290280>,
or mute the thread

**Comment by kimwalisch** [comment]
> This is a very non-standard design. Normally you would create all the
Makefiles, and afterwards make the targets you need.
This is why I was totally at loss what to do in order to run tests, as
there was no Makefile at that directory.

This is a very non-standard design for GNU Autotools projects, but most CMake projects do testing actually the same way, I follow CMake best practices...

**Comment by dimpase** [comment]
no documentation on testing cannot be  best practice anyway  ;-)

I presume the "best" practice you refer to is a leftover from the early
days of cmake, when it was a mostly interactive tool. Naturally one does
not want more interaction then needed, but here it is another story.

**Comment by dimpase** [comment]
Just to mention that all tests pass on SPARC Solaris 11 (using gcc 7.2).

**Comment by kimwalisch** [comment]
> Just to mention that all tests pass on SPARC Solaris 11 (using gcc 7.2).

Thanks! I have a PowerPC (big-endian CPU) running Mac OS X at home and all tests pass there as well.

Based on a suggestion by @jdemeyer https://github.com/kimwalisch/primecount/commit/675756cc6f81dddc56ec5530816799324e4dde0f#commitcomment-28101185 I have changed the memory layout of 2 lookup tables and now the code is endian-safe i.e. there are no more checks for the endianness of the CPU.
