### ISSUE TITLE
Add C API

### ISSUE THREAD

**Issue by AaronChen0** [kimwalisch/primecount#28]
Hi, @kimwalisch. 
Can you add C API as in the case of primesieve?
It's easier for making language bindings with C API.
Thank you.

**Comment by kimwalisch** [comment]
Yes, I can do that!

As I personally think this is a good idea I think that I may even get rid of the C++ API and just offer a C API. I have planned to do a release in a few weeks and this change will be part of the new release.

**Comment by kimwalisch** [comment]
> Can you add C API as in the case of primesieve?

I have now merged the new C API into the master branch. I have decided to keep the old C++ API as some people are already using that API and I don't want to break their code.

The new C API is exposed via the new ```<primecount.h>``` and offers the same functionality as the C++ API. Below is a usage example of the new C API:

```C
#include <primecount.h>
#include <stdio.h>

int main()
{
    int64_t pix = primecount_pi(1000);
    printf("primes below 1000 = %ld\n", pix);

    return 0;
}
```

* [C API reference](https://github.com/kimwalisch/primecount/blob/master/include/primecount.h)
* [libprimecount build instructions](https://github.com/kimwalisch/primecount/blob/master/doc/libprimecount.md)

Could you please have a look at the function declarations and documentation in the [primecount.h](https://github.com/kimwalisch/primecount/blob/master/include/primecount.h) header and let me know if this suits your needs?

**Comment by AaronChen0** [comment]
Excellent! That's exactly what I want. 
I notice the header of primecount.h should be "@file  primecount.h".
Thank you for your great works and the quick response.
