### ISSUE TITLE
Idea for improvement to LMO/pi_lmo5.cpp

### ISSUE THREAD

**Issue by sethtroisi** [kimwalisch/primecount#35]
I was playing around with the timing of your LMO implementation;

https://github.com/kimwalisch/primecount/blob/a7e8351f23ec61d19006c68eaae8bad433d2956e/src/lmo/pi_lmo5.cpp#L56

I noticed that setting `segment_size = 2 * segment_size` seems to run ~2-5% faster 

A couple of random tests suggest that for 1e11 - 1e16 `4 * segment_size` is the sweet spot.

Looking at the code I suspect that there's a trade off between overhead of starting `sieve.cross_off_count` and better localized memory access.

Maybe `get_segment_size` could be augmented with 'suggested_segment_size(limit)` which handles finding a nice power of two or similar number around `sqrt(limit)`. 

Before I went further I thought I should seek your opinion in case this has been tested or there are other issues I'm not aware of.

**Comment by kimwalisch** [comment]
The ```pi_lmo1``` to ```pi_lmo5``` are demonstration implementations, the main goal for these implementations is to be easy to understand and closely match the formulas of the prime counting papers. These implementations are not used internally so that's why improving their speed by a few percent does not matter for primecount's overall speed.

The ```pi_lmo_parallel```, ```pi_deleglise_rivat``` and ```pi_gourdon``` implementations have much more code for finding an ideal segment size: https://github.com/kimwalisch/primecount/blob/v6.0/src/LoadBalancer.cpp#L58. I will try to increase the sieve size there and see if I can get any speedups...

**Comment by sethtroisi** [comment]
I had been looking at `pi_lmo_parallel` too but obviously more moving pieces.

**Comment by kimwalisch** [comment]
In order to e.g. increase the ```segment_size``` for ```pi_lmo_parallel``` (and ```pi_deleglise_rivat``` and ```pi_gourdon```) by 4x you need to change:

```C++
  max_size_ = max(max_size_, sqrt_limit);
  max_size_ = Sieve::get_segment_size(max_size_);
```

to

```C++
  max_size_ = max(max_size_, sqrt_limit);
  max_size_ = Sieve::get_segment_size(max_size_ * 4);
```

On line 75 in LoadBalancer.cpp: https://github.com/kimwalisch/primecount/blob/v6.0/src/LoadBalancer.cpp#L75.

**Comment by kimwalisch** [comment]
My tests indicate that using a larger sieve size than ```sqrt(sieve_limit)``` does not improve performance near 1e18 (tested using the D formula). But what does improve performance and what I already do in LoadBalancer.cpp is if ```sqrt(sieve_limt) < l1_cache_size``` then set ```segment_size=l1_cache_size```. This will ensure optimal cache efficiency for small to medium x < 10^20.

```
  // try to use a segment size that fits exactly
  // into the CPUs L1 data cache
  int64_t l1_dcache_size = 1 << 15;
  max_size_ = l1_dcache_size * 30;
  max_size_ = max(max_size_, sqrt_limit);
  max_size_ = Sieve::get_segment_size(max_size_);
```

I guess this could also be used to speedup ```pi_lmo1``` to ```pi_lmo5``` but as I mentioned before I want to keep the code of these implementations as simple as possible.

**Comment by sethtroisi** [comment]
Thanks for the pointers, explanation, and testing. I'll going to have some fun playing around with LoadBalancer and seeing what happens.
