### ISSUE TITLE
Data Races in LoadBalancerS2.cpp

### ISSUE THREAD

**Issue by markbcahill** [kimwalisch/primecount#42]
Using the Coderrect Scanner [https://coderrect.com/](url) I have discovered three data race pairs occurring in `LoadBalancerS2.cpp`. 
1) Line 96 vs itself
```
 94|{
 95|  LockGuard lockGuard(lock_);
>96|  sum_ += thread.sum;
 97|
 98|  if (is_print_)
```

2) Line 107 vs Line 114
```
 105| update_load_balancing(thread);
 106|
>107| thread.low = low_;
 108| thread.segments = segments_;
 109| thread.segment_size = segment_size_;
 110| thread.sum = 0;
 111| thread.secs = 0;
 112| thread.init_secs = 0;
 113|
>114| low_ += segments_ * segment_size_;
 115| bool is_work = thread.low < sieve_limit_;
 116|
```

3) Line 122 vs Line 124
```
 120|void LoadBalancerS2::update_load_balancing(const ThreadSettings& thread)
 121|{
>122|  if (thread.low > max_low_)
 123|  {
>124|   max_low_ = thread.low;
 125|   segments_ = thread.segments;
 126|
```

**Comment by kimwalisch** [comment]
These are all false positives.

Having a lot of experience with data race detection tools (GCC + LLVM sanitizers, valgrind, ...) myself, I can tell you that these tools are full of bugs and generally generate a lot of false positives. So using these tools is good, but the results have to analysed by an experienced human.

The code below which your tool has marked as data race is a classical example of a best practice on how to avoid data races!

```C++
bool LoadBalancerS2::get_work(ThreadSettings& thread)
{
  // Only one thread at a time can enter this code section.
  // This is done in order to avoid data races when modifying shared global data.
  LockGuard lockGuard(lock_);
  sum_ += thread.sum;
  ...
}

**Comment by markbcahill** [comment]
Alright, thanks for the response. I'm just testing Coderrect, so I am just reporting my findings. If you think this is a false positive, then you likely know better!

**Comment by JakubDrozd** [comment]
@kimwalisch, you can close this issue now.
