### ISSUE TITLE
add pkg-config config?

### ISSUE THREAD

**Issue by dimpase** [kimwalisch/primecount#44]
To facilitate things for non-cmake setups, such as checking the version, setting include and library paths, it would be great to have primecount generating configuration, a .pc file, and installing it in the appropriate location (often it's subdirectory `pkgconfig` of the directory where the library is installed).

**Comment by dimpase** [comment]
see e.g. https://www.scivision.dev/cmake-generate-pkg-config/

**Comment by kimwalisch** [comment]
If you submit a merge request I will gladly merge it. I don't frequently use pkg-config myself, so I would appreciate if you would do the testing.

I guess you could copy/resue most of primesieve's code: [primesieve.pc.in](https://github.com/kimwalisch/primesieve/blob/master/primesieve.pc.in) and [CMakeLists.txt](https://github.com/kimwalisch/primesieve/blob/master/CMakeLists.txt#L312).

**Comment by kimwalisch** [comment]
Tested successfully on Linux and macOS using both GCC & Clang.

**Comment by dimpase** [comment]
Thanks. Do you have timeline for the release of 7.2 ? I know that Debian people are now busy packaging 7.1, perhaps they could wait a bit?

**Comment by kimwalisch** [comment]
> Thanks. Do you have timeline for the release of 7.2 ? I know that Debian people are now busy packaging 7.1, perhaps they could wait a bit?

Yes, personally I think they should wait (and not package 7.1), this way they don't have to do the packaging work twice. I will do a new primesieve and primecount release mid next week.
