### ISSUE TITLE
describing how to build dynamically linked (lib)primecount without root

### ISSUE THREAD

**Issue by dimpase** [kimwalisch/primecount#46]
Playing with cmake a bit, I found how to set up libprimecount and primecount without root, something that's valuable in a number of settings, e.g. on HPC clusters, other shared machines - or building libprimecount extensions (e.g. Python ones).
Should this be added to docs?

The following is only tested on Linux so far.

0. set the desired location, e.g. `export WDIR=$HOME/tmp`
1. install libprimesieve as follows:
```
cd primesieve
cmake -DBUILD_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=$WDIR .
make -j  install     # no sudo!
```
2. install primecount as follows 
```shell
cd primecount
cmake -DBUILD_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=ON \
       -DCMAKE_INSTALL_PREFIX=$WDIR \
      -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE  -DCMAKE_INSTALL_RPATH=$WDIR \
      -DCMAKE_SKIP_BUILD_RPATH=FALSE  -DBUILD_LIBPRIMESIEVE=OFF  \
      -DCMAKE_FIND_ROOT_PATH=$WDIR/lib/cmake  \
      -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY .
make -j install # no sudo!
```
3. done, now you can do `$WDIR/bin/primecount 1000000` and it will work as it should.

**Comment by dimpase** [comment]
this works on macOS too.

**Comment by kimwalisch** [comment]
> Should this be added to docs?

Personally I feel like the documentation should not contain too many expert topics. My documentation is currently written so that beginners and intermediate devs can get started quickly. Expert devs that are e.g. packaging software (or writing bindings) usually know exactly what build settings to use in their particular environment. Even if this piece of information is missing in the documentation experts will likely be able to figure it out quickly by themselves.

**Comment by dimpase** [comment]
> beginners and intermediate devs can get started quickly
No, if you are a primecount beginner wanting to run it without a root access, e.g. a student with access to a shared Unix server, your current docs are not helping, they always have `sudo` in them.
Or assuming one only has an office Linux desktop, centrally managed, thus, no root (that's the case where I work, for instance).

**Comment by isuruf** [comment]
I'm not sure I understand what the issue is.

**Comment by dimpase** [comment]
@isuruf - the question is whether it is well-documented elsewhere how to correctly install  dynamic libs and executables built with cmake if the user does not have root. 

I propose to add such details to the docs here, as it appears tricky. IMHO the standard cmake docs assume that on Linux one installs into /usr/local, using sudo.
