### ISSUE TITLE
brew install on macOS installs primecount 7.0 and no library

### ISSUE THREAD

**Issue by Tiza59** [kimwalisch/primecount#48]
Please update the brew recipe, I have got the following error on M1 Pro Max, Monterey 12.1b3

primecount -n 1000
dyld[11851]: Library not loaded: @rpath/libprimecount.7.dylib
  Referenced from: /opt/homebrew/Cellar/primecount/7.0/bin/primecount
  Reason: tried: '/usr/local/lib/libprimecount.7.dylib' (no such file), '/usr/lib/libprimecount.7.dylib' (no such file)

**Comment by kimwalisch** [comment]
I was able to reproduce your issue on an M1 Mac Mini:

```
% otool -L /opt/homebrew/Cellar/primecount/7.0/bin/primecount
/opt/homebrew/Cellar/primecount/7.0/bin/primecount:
	@rpath/libprimecount.7.dylib (compatibility version 7.0.0, current version 7.0.0)
	/opt/homebrew/opt/primesieve/lib/libprimesieve.9.dylib (compatibility version 9.0.0, current version 9.7.0)
	/opt/homebrew/opt/llvm/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

The current rpath setting expects libprimecount.7.dylib to be located at ```/opt/homebrew/Cellar/primecount/7.0/bin``` however it is located ìn another directory: ```/opt/homebrew/Cellar/primecount/7.0/lib```. This bug happens because primecount is an unofficial homebrew package (tab) and not a regular homebrew package.

I will try to link libprimecount statically into the primecount binary on macOS and alter the rpath settings.

**Comment by Tiza59** [comment]
@kimwalisch Thanks a lot!

**Comment by kimwalisch** [comment]
I have fixed the issue and released primecount-7.2 on homebrew. libprimecount is now statically linked into the primecount binary on macOS, hence the primecount binary does not have a dependency on libprimecount anymore as can be seen using tool below:

```
 % otool -L /opt/homebrew/Cellar/primecount/7.2/bin/primecount
/opt/homebrew/Cellar/primecount/7.2/bin/primecount:
	/opt/homebrew/opt/primesieve/lib/libprimesieve.9.dylib (compatibility version 9.0.0, current version 9.7.0)
	/opt/homebrew/opt/llvm/lib/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/homebrew/opt/llvm/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

I think you can update to the latest primecount version on your Mac using:

```
brew update
brew upgrade
```

**Comment by kimwalisch** [comment]
P.S. I recommend running primecount using the ```--status```, it is more fun....

**Comment by Tiza59** [comment]
Thanks again, works perfectly.
