### ISSUE TITLE
Question regarding PhiTiny _sieve array

### ISSUE THREAD

**Issue by JakubDrozd** [kimwalisch/primecount#49]
Hi @kimwalisch, I would like to see the full content of the PhiTiny sieve array, because it seems that it is all zero. Could you send it to me? I would be grateful.

**Comment by kimwalisch** [comment]
Hi Jakub,

> I would like to see the full content of the PhiTiny sieve array, because it seems that it is all zero. Could you send it to me? I would be grateful.

The values of phi(x, a) are in the ```PhiTiny::phi_[a][x]``` array (note that the order of x & a is swapped). The ```PhiTiny::sieve_``` array is a compressed lookup table of phi(x, a) values that allows using larger phi(x, a) lookup tables in primecount (it is a performance optimization).

In order to study the algorithm it is best to forget about the ```sieve```array and instead focus on understanding how the ```PhiTiny::phi_[a][x]``` array is filled. I suggest you study some older version of this code (version 7.0) when the sieve array did not yet exist (It is much easier to understand):

* https://github.com/kimwalisch/primecount/blob/v7.0/src/PhiTiny.cpp#L42

> Could you send it to me?

No, you will have to figure it out yourself ;-)

**Comment by JakubDrozd** [comment]
Just I would like to see the values because it seems to me that it is all zero.

**Comment by kimwalisch** [comment]
> Just I would like to see the values because it seems to me that it is all zero.

The sieve array is only used for a > 5 (therefore these values are likely missing in the sieve array) for smaller values of a the phi_ lookup table is used instead. See here:

* https://github.com/kimwalisch/primecount/blob/master/include/PhiTiny.hpp#L72

**Comment by JakubDrozd** [comment]
But even in the a > 5 case it is all zero!

**Comment by kimwalisch** [comment]
In your implementation or in primecount's implementation?

In primecount's implementation the following line in PhiTiny.cpp initializes all bits with 1:

```
sieve_[a].resize(size);
```

This is because of the default constructor of the sieve:

```
  struct sieve_t
  {
    uint32_t count = 0;
    uint64_t bits = ~0ull;
  };
```

Is that your issue? I guess I should add a comment to the code?

**Comment by JakubDrozd** [comment]
Yes, I haven't seen the default constructor. Thank you! And I have just one thing: could you open discussions so I wouldn't need to open issues? I would really appreciate.

**Comment by JakubDrozd** [comment]
> In primecount's implementation the following line in PhiTiny.cpp initializes all bits with 1:
It seems that it initialises the bits property with 18446744073709551615, not 1.

**Comment by kimwalisch** [comment]
> It seems that it initialises the bits property with 18446744073709551615, not 1.

Yes, all bits are set to 1, sieve.bits is a 64-bit variable so it contains 64 1-bits after initialization. After initialization the sieve array looks like : {{0, 18446744073709551615}, {0, 18446744073709551615}, {0, 18446744073709551615}, {0, 18446744073709551615}, ...} .

**Comment by JakubDrozd** [comment]
It seems when I run my code (a re-implementation of the PhiTiny constructor, it gives me the count is 0 and the bits are all 0. Can you tell me why?

**Comment by kimwalisch** [comment]
Note that the PhiTiny::sieve_ compressed lookup table does not provide much speedup (likely even none in your implementation). It is a lot of work to implement it and unless your implementation uses the POPCNT instruction it will almost likely run slower. You should strongly consider using only the basic non-compressed PhiTiny::phi_ lookup table (check code of primecount-7.0).

You are on your own from now on...

**Comment by JakubDrozd** [comment]
Thank you! And one bonus: you can contribute to my implementation! Just follow the link: https://github.com/JakubDrozd/JSprimecount/invitations

**Comment by JakubDrozd** [comment]
@kimwalisch you have an invitation!

**Comment by JakubDrozd** [comment]
@kimwalisch Thank you! And one bonus: you can contribute to my implementation! Just follow the link: https://github.com/JakubDrozd/JSprimecount/invitations.
Please reply when you accept the invitation.
