### ISSUE TITLE
xavier gourdon's paper

### ISSUE THREAD

**Issue by hrichharms** [kimwalisch/primecount#62]
I can't seem to find [reference 7](https://github.com/kimwalisch/primecount/blob/master/doc/References.md) anywhere on the internet. Does anyone have a link I can go to or a pdf I can read to get a better understanding of the algorithm?

**Comment by kimwalisch** [comment]
You can download the paper here: http://numbers.computation.free.fr/Constants/constants.html

Or from my Google Drive: https://drive.google.com/file/d/0B5Y5VYcy13QxN2FhZGM5NjUtNzFiMi00ZGJjLWJiMjItNjJiMTY3ZjlmZmM2/view?usp=sharing&resourcekey=0-4jb66koXPiYCgkFiDWbASg

**Comment by hrichharms** [comment]
thank you ^_^

**Comment by KStarGamer** [comment]
A new paper has been uploaded to arXiv which claims to improve on the current best algorithm for calculating the prime counting function (it also references your GitHub page). Thought I’d share it here in case you hadn’t seen it yet: https://arxiv.org/abs/2212.09857
