### ISSUE TITLE
prime_pi of a negative number fails with Bus error

### ISSUE THREAD

**Issue by mezzarobba** [kimwalisch/primecount#64]
As reported by @remyoudompheng at https://github.com/sagemath/sage/issues/35332, `prime_pi` crashes on negative input. (I think this is true of the 128 bit variant too.)
```
$ cat sage_bug_35332.c
#include <primecount.h>
#include <stdio.h>

int main()
{
    int64_t pix = primecount_pi(-1);
    printf("primes <= -1: %ld\n", pix);

    return 0;
}
$ gcc sage_bug_35332.c -lprimecount && ./a.out
Bus error (core dumped)
(exit 135)
```

**Comment by kimwalisch** [comment]
I was able to reproduce the issue and get a stack trace of the bug:

```
#7  0x000055555555d628 in primecount::pod_array<primecount::PiTable::pi_t, 64ul>::operator[] (this=0x5555555faa20 <primecount::PiTable::pi_cache_>, pos=76861433640456465)
    at /home/kim/primecount/include/pod_vector.hpp:398
#8  0x000055555555d304 in primecount::PiTable::pi_cache (x=18446744073709551615) at /home/kim/primecount/include/PiTable.hpp:64
#9  0x000055555555c9e3 in primecount::pi_cache (x=-1, is_print=false) at /home/kim/primecount/src/api.cpp:49
#10 0x000055555555ca61 in primecount::pi (x=-1, threads=3) at /home/kim/primecount/src/api.cpp:61
#11 0x000055555555ca26 in primecount::pi (x=-1) at /home/kim/primecount/src/api.cpp:54
#12 0x000055555555c7cd in main () at /home/kim/primecount/test/api.cpp:36
```

The bug is caused by ```pi_cache(x)``` not having a check for negative inputs. All other ```pi*(x)``` functions have such a check.

```pi_cache(x)``` is an internal function, I have think about whether I want the if check there or in the calling/parent ```pi(x)``` function.

**Comment by kimwalisch** [comment]
Is ```pi(-1) = 0``` OK for you or do you need some other behavior?
Currently nearly all internal ```pi(x)``` functions return 0 for negative inputs, without reporting any error.

**Comment by kimwalisch** [comment]
I have fixed the bug, I will likely do a new release next week.

**Comment by mezzarobba** [comment]
On Friday, 24 March 2023 19:31:01 CET Kim Walisch wrote:
> Is ```pi(-1) = 0``` OK for you or do you need some other behavior?

Yes, I think returning 0 is the natural thing to do.

**Comment by kimwalisch** [comment]
Unfortunately, primecount-7.7 did not entirely fix the issue: pi(x) still reports incorrect results for x <= -2^63 (e.g. pi("-1267650600228229401496703205373") returns 2 using primecount-7.7). I have fixed that issue as well this morning and added more tests.

I will likely release primecount-7.8 later today or tomorrow.
